import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import UserMenu from "./components/UserMenu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900">
        <nav className="bg-blue-600 p-4 text-white shadow-md">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">Absensi Admin</h1>
            <div className="space-x-4">
              <a href="/" className="hover:underline">Dashboard</a>
              <a href="/guru" className="hover:underline">Manajemen Guru</a>
              <a href="/dispensasi" className="hover:underline">
                Manajemen Dispensasi
              </a>
              <UserMenu />
            </div>
          </div>
        </nav>
        <main className="container mx-auto p-6 flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
